name: sub_trackr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  installed_apps: ^1.6.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

